In [2]:
import tensorflow as tf
import numpy as np

x_data = np.array([[0,0], [0,1], [1,0], [1,1]])
y_data = np.array([[0], [1], [1], [0]])

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))

h = tf.matmul(W, X)
hypothesis = tf.div(1., 1.+tf.exp(-h))

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

a = tf.Variable(0.01)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(100001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            sess.run([hypothesis, cost], feed_dict={X:x_data, Y:y_data})
            correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)
            accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
            
            print ('\n')
            print (step)
            print (sess.run(hypothesis, feed_dict={X:x_data, Y:y_data}))
            print ("Acc : ", accuracy.eval({X:x_data, Y:y_data}))



0
[[ 0.33156788  0.26859859]]
Acc :  0.5


2000
[[ 0.5030542   0.49670452]]
Acc :  0.5


4000
[[ 0.50025988  0.4997395 ]]
Acc :  0.5


6000
[[ 0.50002134  0.4999786 ]]
Acc :  0.5


8000
[[ 0.50000161  0.49999839]]
Acc :  0.5


10000
[[ 0.50000149  0.49999851]]
Acc :  0.5


12000
[[ 0.50000149  0.49999851]]
Acc :  0.5


14000
[[ 0.50000149  0.49999851]]
Acc :  0.5


16000
[[ 0.50000149  0.49999851]]
Acc :  0.5


18000
[[ 0.50000149  0.49999851]]
Acc :  0.5


20000
[[ 0.50000149  0.49999851]]
Acc :  0.5


22000
[[ 0.50000149  0.49999851]]
Acc :  0.5


24000
[[ 0.50000149  0.49999851]]
Acc :  0.5


26000
[[ 0.50000149  0.49999851]]
Acc :  0.5


28000
[[ 0.50000149  0.49999851]]
Acc :  0.5


30000
[[ 0.50000149  0.49999851]]
Acc :  0.5


32000
[[ 0.50000149  0.49999851]]
Acc :  0.5


34000
[[ 0.50000149  0.49999851]]
Acc :  0.5


36000
[[ 0.50000149  0.49999851]]
Acc :  0.5


38000
[[ 0.50000149  0.49999851]]
Acc :  0.5


40000
[[ 0.50000149  0.49999851]]
Acc :  0.5


42000
[[ 0.50000149