In [3]:
import tensorflow as tf
import numpy as np

x_data = np.array([[0,0], [0,1], [1,0], [1,1]])
y_data = np.array([[0], [1], [1], [0]])

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2, 2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform([2, 1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name = "Bias1")
b2 = tf.Variable(tf.zeros([1]), name = "Bias2")

L2 = tf.sigmoid(tf.matmul(X, W1) + b1)
hypothesis = tf.sigmoid(tf.matmul(L2, W2) + b2)

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

a = tf.Variable(0.01)

optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    for step in range(100001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        if step % 2000 == 0:
            sess.run([hypothesis, cost], feed_dict={X:x_data, Y:y_data})
            correct_prediction = tf.equal(tf.floor(hypothesis+0.5), Y)
            accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
            
            print ('\n')
            print (step)
            print (sess.run(hypothesis, feed_dict={X:x_data, Y:y_data}))
            print ("Acc : ", accuracy.eval({X:x_data, Y:y_data}))



0
[[ 0.44400185]
 [ 0.46767116]
 [ 0.49170014]
 [ 0.51279646]]
Acc :  0.25


2000
[[ 0.46296206]
 [ 0.49044451]
 [ 0.51234841]
 [ 0.53499418]]
Acc :  0.5


4000
[[ 0.45935857]
 [ 0.49273556]
 [ 0.51207459]
 [ 0.53704888]]
Acc :  0.5


6000
[[ 0.45320046]
 [ 0.49511433]
 [ 0.51280588]
 [ 0.53991443]]
Acc :  0.5


8000
[[ 0.44344348]
 [ 0.49805886]
 [ 0.51485026]
 [ 0.54357648]]
Acc :  0.5


10000
[[ 0.4286074 ]
 [ 0.50217247]
 [ 0.51870441]
 [ 0.5484224 ]]
Acc :  0.75


12000
[[ 0.40659603]
 [ 0.50819278]
 [ 0.52508819]
 [ 0.55538881]]
Acc :  0.75


14000
[[ 0.37496617]
 [ 0.51700413]
 [ 0.53500462]
 [ 0.56552172]]
Acc :  0.75


16000
[[ 0.33290723]
 [ 0.52933568]
 [ 0.54946333]
 [ 0.57895374]]
Acc :  0.75


18000
[[ 0.28421474]
 [ 0.54476088]
 [ 0.56845778]
 [ 0.59376013]]
Acc :  0.75


20000
[[ 0.23640771]
 [ 0.56112045]
 [ 0.59036863]
 [ 0.60650498]]
Acc :  0.75


22000
[[ 0.19558904]
 [ 0.57582569]
 [ 0.61325473]
 [ 0.61459678]]
Acc :  0.75


24000
[[ 0.1638587 ]
 [ 0.5874598 ]
 [